name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mitraai-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mitraai-frontend:latest